### ISSUE TITLE
nuxt3 Failed to resolve component: Renderer

### ISSUE THREAD

**Issue by differentMonster** [troisjs/trois#100]
Hello guys, i am trying to make a Nuxt3-troisjs for use but face this problem, the 3D load i keep seeing this error on my terminal, i tried to input components on the plugins but still didt remove the error.

```
[Vue warn]: Failed to resolve component: Renderer
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

do anyone face this problem by input into nuxt3 ?

github : https://github.com/differentMonster/nuxt3-troisjs

**Comment by klevron** [comment]
https://github.com/differentMonster/nuxt3-troisjs/blob/master/frontend/plugins/troisjs.client.js#L5

`createTroisJS` does not exist, where did you find this code ??

Here is a working nuxt3 example : https://github.com/troisjs/nuxt3-test

**Comment by klevron** [comment]
Here is an example of plugin :

```js
import { defineNuxtPlugin } from '#app'

import {
    Box,
    Camera,
    LambertMaterial,
    PointLight,
    Renderer,
    Scene
} from 'troisjs'

export default defineNuxtPlugin(({ vueApp }) => {
    vueApp.component('Box', Box)
    vueApp.component('Camera', Camera)
    vueApp.component('LambertMaterial', LambertMaterial)
    vueApp.component('PointLight', PointLight)
    vueApp.component('Renderer', Renderer)
    vueApp.component('Scene', Scene)
})
```

**Comment by differentMonster** [comment]
@klevron i acutally forgot where i got that, but i saw a person github similar like that so i tried it out but of course i mess up, now looking back to those code, it make no sense to me, you plugin have much more clear input to nuxt3. really thanks for helping, i really like your this plugin of yours.

**Comment by differentMonster** [comment]
Well the error still there after changing the the plugins to yours, i am not sure what is was causing it.
