### ISSUE TITLE
Adding PointLightHelper and CameraHelper fails

### ISSUE THREAD

**Issue by Camil88** [troisjs/trois#111]
Hello, when I add mentioned helpers to my `mounted()` section then the following erros come up in the console:

> [Vue warn]: Unhandled error during execution of mounted hook
> TypeError: this.light.updateMatrixWorld is not a function

My code below:
```js
<script>
import { Camera, Scene, Renderer, PointLight, LambertMaterial, Plane } from 'troisjs';
import { GridHelper, AxesHelper, Vector3, PointLightHelper, CameraHelper } from 'three';

export default {
  name: 'BaseModel',
  components: {
  Camera, Scene, Renderer, PointLight, LambertMaterial, Plane
  },

// here is some data() elements etc..

  mounted() {
    const renderer = this.$refs.renderer;
    const scene = this.$refs.scene;
    const camera = this.$refs.camera;
    const light = this.$refs.light;

    const pointLightHelper = new PointLightHelper(light, 1)
    scene.add(pointLightHelper)

    const cameraHelper = new CameraHelper(camera)
    scene.add(cameraHelper)

    renderer.onBeforeRender(() => {
      }
    )
  }
}
</script>
```
It's worth adding, that the problem is not arising when I add helpers to my another, pure Three.js project. It's a problem in Trois.js I guess. Or maybe I should not add those heleprs to `mounted()`?

**Comment by klevron** [comment]
`const camera = this.$refs.camera;` => camera will be the vuejs component, not threejs object.

I know it is a little bit confusing but you have to use : `this.$refs.camera.camera` and `this.$refs.light.light`

**Comment by Camil88** [comment]
Thanks, it works. However I don't truly understand why I need to 'double' object name e.g. `this.$refs.camera.camera`. For example, it's fine when I use  only `this.$refs.renderer` - I don't need to add extra `.renederer` to make my code work. Same with `this.$refs.scene`. Could you explain it a little wider in Trois.js documentation or here? Basically, what's the difference between e.g. `this.$refs.camera.camera` and `this.$refs.camera` or `this.$refs.renderer.renderer` and `this.$refs.renderer`?

**Comment by klevron** [comment]
- If you want to use vuejs component, you have to use `this.$refs.renderer`
- If you want to use threejs object methods you have to `this.$refs.renderer.renderer`

One simple example : `onBeforeRender` is a method from vuejs component, not from threejs renderer object.

**Comment by Camil88** [comment]
Ok, it's clear now, thanks
