### ISSUE TITLE
Question: ExtrudeGeometry in Troisjs

### ISSUE THREAD

**Issue by Taso69** [troisjs/trois#112]
I'm trying to display a field of stars (simple five-pointed star polygon), and I can't seem to be able to make with the available geometries.
Looking at three.js, I would be able to do this with an ExtrudeGeometry or a ShapeGeometry (+ InstancedMesh), however these geometries are not available directly in trois.

Is there a specific reason for this ?
Is there another way I'd be able to achieve this with what's available in trois ?

**Comment by klevron** [comment]
It could be useful, I'll try to add this to the next release.

But you can still use a custom geometry, like this : https://github.com/troisjs/flower
