### ISSUE TITLE
Typescript class api

### ISSUE THREAD

**Issue by davidmoshal** [troisjs/trois#118]
Hi, wondering if this library would work with Vue 2, ie: If I replaced the Vue 3 depency.

Reason is that I'd like to use the vue-class-component and vue-property-decorator libraries for Vue/Ts classes.  
It seems that these are not supported by Vue3?

Thanks for the great project!

**Comment by SaFrMo** [comment]
Unfortunately this library won't work with Vue 2 - there are a lot of Vue 3-specific methods in use (lots of provide/inject, etc) that won't translate. Working with TS in Vue 3 is definitely possible, so you may be able to accomplish something similar to what you have in mind out of the box in Vue 3, but it wouldn't be doable by swapping out the Vue version with Trois. Sorry about that!
