### ISSUE TITLE
How to resize gtlf model in troisjs

### ISSUE THREAD

**Issue by Huang-Shijie-SDUWH** [troisjs/trois#125]
My gltf model seems too big too show in my view, I'm trying to find some way to decrease it's scale.
![image](https://user-images.githubusercontent.com/57386430/152752974-a125ce03-9112-4c54-83ca-006dac5aae6c.png)

But things are not going easy, as a beginner in javascript, I've tried some ways according to threejs docmentation and troisjs documetation and even on stackoverflow, including use "multiplyScalar" in the <Camera> object and rescale the gtlf loader, none of them work well.

Could you provide a simple way to do this job? Many thanks if you can help.

**Comment by klevron** [comment]
You can simply use scale property : `:scale="{ x: 0.5, y: 0.5, z: 0.5 }"`
