### ISSUE TITLE
Renderer props width and height expecting the wrong type

### ISSUE THREAD

**Issue by VandrerenErik** [troisjs/trois#128]
Versions:

"three": "0.134",
"troisjs": "^0.3.4",

When sending a Number as specified in the docs and as common sense dictates I get the following warning (image below) telling me that a String is expected instead. I'm pretty sure this is clearly a bug.

![image](https://user-images.githubusercontent.com/54407345/158474280-23de0111-945e-441b-a8a7-ef4fe8f93d42.png)

**Comment by klevron** [comment]
Did you try with `:width="300"` ?

**Comment by VandrerenErik** [comment]
> Did you try with `:width="300"` ?

If you read the warning and what I said, the problem is that Trois is expecting a String, it should be expecting a Number

**Comment by VandrerenErik** [comment]
You made a mistake here

https://github.com/troisjs/trois/blob/master/src/core/Renderer.ts

Width and Height should be "Numbers"

**Comment by klevron** [comment]
Not really a mistake :  https://github.com/troisjs/trois/blob/master/src/core/Renderer.ts#L145

**Comment by VandrerenErik** [comment]
Mate, that is just bad codig... I'll assume you're a rookie in the field. Have a good day.
