### ISSUE TITLE
How to place trois Renderer into an HTML element by id

### ISSUE THREAD

**Issue by EFeru** [troisjs/trois#129]
Hi,
Thank you for your work. I was trying to place one of the vue components [from here](https://github.com/troisjs/troisjs.github.io/tree/master/src/components/demos) into my website header which has an id but without success.
Any idea how to do it?

I tryied the code below added in the component vue file itself, e.g., in `Demo4.vue`:
```js
mounted() {
    //... code from Demo4.vue
    const renderer = this.$refs.renderer;
    var container = document.getElementById('mastheadBackground'); // 'mastheadBackground' is my header id
    container.appendChild(renderer.domElement);
}
```

The animation appears at the end of the website but not in the header element. In the console, the folowing error is shown:
![image](https://user-images.githubusercontent.com/24780745/159545880-729093d9-58fc-4d0f-a9be-c83ab6f43300.png)

 Any help is appreciated. Thanks!

**Comment by Lightnet** [comment]
Did you try this?
`container.appendChild(renderer);`

**Comment by EFeru** [comment]
@Lightnet thanks a lot, it is now displayed on the header!
One issue still left is it does not ocuppy fully the container space.
![image](https://user-images.githubusercontent.com/24780745/159577222-5546b5d5-6cc0-42cd-839d-d320294729bb.png)

I already tryied adding `resize="window"` in the Renderer:
```html
<template>
  <Renderer ref="renderer" resize="window" :orbit-ctrl="{ enableDamping: true, dampingFactor: 0.05, autoRotate : true }" shadow>
    <Camera :position="{ y: 100, z: 100 }" />
    <Scene>
      <SpotLight color="#ffffff" :intensity="0.5" :position="{ y: 150, z: 0 }" :cast-shadow="true" :shadow-map-size="{ width: 1024, height: 1024 }" />
      <SpotLight color="#ff0000" :intensity="0.5" :position="{ y: -150, z: 0 }" :cast-shadow="true" :shadow-map-size="{ width: 1024, height: 1024 }" />
      <InstancedMesh ref="imesh" :count="NUM_INSTANCES" :cast-shadow="true" :receive-shadow="true">
        <SphereGeometry :radius="5" />
        <PhongMaterial />
      </InstancedMesh>
    </Scene>
    <EffectComposer>
      <RenderPass />
      <UnrealBloomPass :strength="2" />
    </EffectComposer>
  </Renderer>
</template>
```
However, then I get full width but not full height occupied.
![image](https://user-images.githubusercontent.com/24780745/159577350-0ec43c3f-da1a-4c6b-8b80-faa0f01c4669.png)

Any idea how to approach it?

**Comment by Lightnet** [comment]
If you on chrome browser you try inspect your element. Hover over the element to see the height of parent to children by layers. Html, body and #app #root div effect your size screen a bit. The height is base on the current content.

Try this as it work for me as it resize base on parent div.
`<Renderer ref="renderer"  resize="div" >`

It the same problem with threejs. It should be similar. Just edit the css file or style.

**Comment by klevron** [comment]
Di you tried https://vuejs.org/guide/built-ins/teleport.html ? (never tried)

**Comment by EFeru** [comment]
Thanks @klevron I will give it a try.
@Lightnet the `resize="div"` did not work as expected, it behave similar to `resize="window"` but I have to check a bit more to be sure.

**Comment by Lightnet** [comment]
I was curios about trying out since I need to resize to div for building for my project.  resize="div"

**Comment by Lightnet** [comment]
Oh right I forgot that you need to calculate the header image to adjust the height. I had to reread your post. You need image height to fit correctly with renderer.
```
<div style="height:100%">
  <img src="" height="180px">
  <div style="height:calc(100% - 180px)">
    <canvas>
  </div>
</div>
```
This should work.

**Comment by EFeru** [comment]
Not sure if I understand where to place the code above. I have my image specified in the scss file:
```css
header.masthead {
    padding-top: 6rem + 4.5rem;
    padding-bottom: 6rem;
    text-align: center;
    color: $white;
    background-image: url('~@/assets/img/header-bg.jpg');
    background-repeat: no-repeat;
    background-attachment: scroll;
    background-position: center center;
    background-size: cover;
```
