### ISSUE TITLE
individually color faces of an instanced cube

### ISSUE THREAD

**Issue by philbroberts** [troisjs/trois#13]
Thanks for this great package and the beautiful demos.  I've had great fun playing with it over the past week.  

Is it possible to individually shade the faces of an instanced cube?  In a regular threejs project, I use the method described here: https://stackoverflow.com/questions/44828713/paint-cube-faces-as-a-whole-not-the-triangles-that-make-up-the-face-three-js/44836160#44836160.  It seems the geometry is tied together with the material.  I'm not sure how to do that with the vue component design paradigm.  Thanks for any guidance or suggestions.

**Comment by klevron** [comment]
Thanks for playing with TroisJS :)

This method won't work with an InstancedMesh, I think you need a custom shader for this

**Comment by philbroberts** [comment]
Thanks for your help.  I will pursue that direction.
