### ISSUE TITLE
Draco supporting

### ISSUE THREAD

**Issue by Aziz87** [troisjs/trois#151]
If you need use DracoLoader

`
 <GltfModel src="/models/optimized/VIKING/BODY/VIKING_BODY_1.glb"
                 @beforeLoad="initDraco">
`

`methods:{
    initDraco(loader){
      const dracoLoader = new DRACOLoader();
      dracoLoader.setDecoderPath('https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/js/libs/draco/'); // use a full url path
      loader.setDRACOLoader(dracoLoader);
    }
  }`

**Comment by Aziz87** [comment]
is recept

**Comment by bluelemonade** [comment]
hi,

I tried to import the dracoloader.js, but where can I find it?

[<GltfModel src="./export-bibel-3/Bibel30kPBR_2048.glb" @load="onReady" @beforeLoad="initDraco" @progress="onProgress" @error="onError" :rotation="{ x: 0, z: 0 }"/>](url)



in vue3 
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
```
const initDraco = () => {  // loader
      const dracoLoader = new DRACOLoader(); 
      dracoLoader.setDecoderPath('https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/js/libs/draco/');
    }
```

i got:

onError Error: THREE.GLTFLoader: No DRACOLoader instance provided.
    at new GLTFDracoMeshCompressionExtension (GLTFLoader.js?34ad:1305:1)
    at GLTFLoader.parse (GLTFLoader.js?34ad:357:1)
    at Object.eval [as onLoad] (GLTFLoader.js?34ad:194:1)
    at eval (three.module.js?5a89:38709:1)

how can i load this file in troiejs
