### ISSUE TITLE
How to add css2drenderer? I tried to add it in onbeforerender, but it didn't show the effect. Thank you

### ISSUE THREAD

**Issue by Iceberg606** [troisjs/trois#156]
How to add css2drenderer? I tried to add it in onbeforerender, but it didn't show the effect. Thank you

**Comment by Iceberg606** [comment]
its ok

**Comment by amirofski** [comment]
CSS2DRenderer is a simplified version of CSS3DRenderer. The only transformation that is supported is translation. <br/>
I think This link can help you: [https://threejs.org/docs/#examples/en/renderers/CSS2DRenderer](https://threejs.org/docs/#examples/en/renderers/CSS2DRenderer)

**Comment by Iceberg606** [comment]
> CSS2DRenderer is a simplified version of CSS3DRenderer. The only transformation that is supported is translation. I think This link can help you: https://threejs.org/docs/#examples/en/renderers/CSS2DRenderer

thank you！
