### ISSUE TITLE
Nuxt3 build  ERROR  [commonjs--resolver]

### ISSUE THREAD

**Issue by jojco** [troisjs/trois#164]
Hi, I have problem during building process on Nuxt3. 
Can somebody help me?

my package.json
``` json
{
  "devDependencies": {
    "nuxt": "3.0.0-rc.11",
  },
  "dependencies": {
    "three": "^0.143.0",
    "troisjs": "^0.3.4"
  }
}
```
``` bash
ℹ Client built in 16353ms                                                                                                                                                                                                12:01:06
ℹ Building server...                                                                                                                                                                                                     12:01:06

 ERROR  [commonjs--resolver] Unexpected keyword 'false'                                                                                                                                                                  12:01:13
file: /app/node_modules/troisjs/build/trois.module.js:629:13
627:       this.addListener("init", cb);
628:     },
629:     onMounted(cb) {
                  ^
630:       this.addListener("mounted", cb);
631:     },


 ERROR  Unexpected keyword 'false'                    
```

**Comment by arcyleung** [comment]
There is something strange happening in Rollup or one of the plugins, causing the source to become transformed into "false && onMounted(cb)"
![image](https://user-images.githubusercontent.com/7380279/196060210-d27cadbe-abf0-4282-8a77-f34d0d2984e2.png)

More specifically this line in rollup.js throws the error, I am no expert but will try to dig further.
![image](https://user-images.githubusercontent.com/7380279/196060319-0df6efa8-3c1f-47d4-b485-c9aa5d3339e9.png)

**Comment by andysay** [comment]
do you create post on nuxt3 repo?

**Comment by jojco** [comment]
In my case I had <ClientOnly> component in the parent component and I thought child component will inherit
from it, but It looks like I was wrong. I take <ClientOnly> directly before <Renderer> in the one component (or .client postfix on component), after that everything works fine. My fault.

**Comment by arcyleung** [comment]
For my case, I resolved it by adding `transpile: ['troisjs']` into my `nuxt.config.ts` build options as specified in [this doc](https://nuxtjs.org/docs/directory-structure/plugins/#name-conventional-plugin). I had forgotten it was a module!
![image](https://user-images.githubusercontent.com/7380279/198505773-018bc3a5-0fb0-42f1-8f2e-dcfe6f0f256e.png)

**Comment by jojco** [comment]
> For my case, I resolved it by adding `transpile: ['troisjs']` into my `nuxt.config.ts` build options as specified in [this doc](https://nuxtjs.org/docs/directory-structure/plugins/#name-conventional-plugin). I had forgotten it was a module! ![image](https://user-images.githubusercontent.com/7380279/198505773-018bc3a5-0fb0-42f1-8f2e-dcfe6f0f256e.png)

I already had set this before, but yes It can have same result if you don't have this settings.

**Comment by insyri** [comment]
> In my case I had component in the parent component and I thought child component will inherit from it, but It looks like I was wrong. I take directly before in the one component (or .client postfix on component), after that everything works fine. My fault.

Could you expand on this? I'm having this issue as well and I'm having trouble following your comment here.

**Comment by jojco** [comment]
> > In my case I had component in the parent component and I thought child component will inherit from it, but It looks like I was wrong. I take directly before in the one component (or .client postfix on component), after that everything works fine. My fault.
> 
> Could you expand on this? I'm having this issue as well and I'm having trouble following your comment here.

I had Nuxt set on hybrid rendering ssr: true. And I had <ClientOnly> component in separate .vue file where was child component renderer.vue  inside them I had <Renderer> troisjs component. This was wrong ,after I put <ClientComponent> directly inside renderer.vue before <Renderer>, everything works fine. (Remember you must have build: { transpile:['troijs'] } as well.)

**Comment by mateoKutnjak** [comment]
> > > In my case I had component in the parent component and I thought child component will inherit from it, but It looks like I was wrong. I take directly before in the one component (or .client postfix on component), after that everything works fine. My fault.
> > 
> > 
> > Could you expand on this? I'm having this issue as well and I'm having trouble following your comment here.
> 
> I had Nuxt set on hybrid rendering ssr: true. And I had component in separate .vue file where was child component renderer.vue inside them I had troisjs component. This was wrong ,after I put directly inside renderer.vue before , everything works fine. (Remember you must have build: { transpile:['troijs'] } as well.)

So you put <ClientOnly> html tag inside .vue component file which used Trois.js renderer?

So I should NOT do something like 

```
<ClientOnly>
   <ComponentWhichUsesTroisJSRenderer/>
</ClientOnly>
```

**Comment by insyri** [comment]
From what I'm seeing, no. You want everything troisjs related client side.

Sidenote, I switched to another website framework; I couldn't resolve this issue for about 3 weeks.

**Comment by mateoKutnjak** [comment]
Which one?

**Comment by insyri** [comment]
Not Nuxt and not Vue; I'm not using troisjs either.

**Comment by jojco** [comment]
> > > > In my case I had component in the parent component and I thought child component will inherit from it, but It looks like I was wrong. I take directly before in the one component (or .client postfix on component), after that everything works fine. My fault.
> > > 
> > > 
> > > Could you expand on this? I'm having this issue as well and I'm having trouble following your comment here.
> > 
> > 
> > I had Nuxt set on hybrid rendering ssr: true. And I had component in separate .vue file where was child component renderer.vue inside them I had troisjs component. This was wrong ,after I put directly inside renderer.vue before , everything works fine. (Remember you must have build: { transpile:['troijs'] } as well.)
> 
> So you put html tag inside .vue component file which used Trois.js renderer?
> 
> So I should NOT do something like
> 
> ```
> <ClientOnly>
>    <ComponentWhichUsesTroisJSRenderer/>
> </ClientOnly>
> ```

Yes exactly.
You should use something like
```vue
<ClientOnly>
  <Renderer>
    <Scene/>
    ...
  </Renderer>
</ClientOnly>
```

And remember as well transpile it.

Sorry for the late reply, I'm already building similar library from the scratch. 
Do you solve it ?

**Comment by cccccccccccccccccnrd** [comment]
Still having this issue -- any updates on this?
