### ISSUE TITLE
How to use OrthographicCamera instead of PerspectiveCamera

### ISSUE THREAD

**Issue by aalolexx** [troisjs/trois#200]
Hello Everyone,

I am trying to use the OrthographicCamera instead of the PerspectiveCamera.
However, looking at the documentation, it seems that trois only supports the Perspective Camera. ([see here](https://troisjs.github.io/guide/core/camera.html)).

I also tried to just add the OrthographicCamera per JS, but this doesn't seem to work since trois js searches for it's own camera object and returns an error.

Is there a way to use the OrtohographicCamera somehow?

Best regards and thanks in advance.

**Comment by aalolexx** [comment]
My Apologies. The camera actually exists and is usable by importing ``import { OrthographicCamera } from 'troisjs';``

**Comment by khaledOghli** [comment]
I suggest to Go with tresjs instead of troisjs
