### ISSUE TITLE
Resize canvas when DOM parent changes size

### ISSUE THREAD

**Issue by christian-nils** [troisjs/trois#24]
Hello,

I am wondering if there is an easy way to resize the canvas when the DOM parent of the canvas is changed. As it is now, a "resize" listener is set on the windows and the "onResize()" method is not exposed. 

What would be the cleanest way to do it?

Thanks,

/CN

**Comment by klevron** [comment]
Hello

What version do you use ?
Did you try to set resize on renderer :
```
<Renderer resize>
</Renderer>
```

https://troisjs.github.io/guide/usage/renderer.html
https://github.com/troisjs/trois/blob/master/src/core/Renderer.js#L70

**Comment by christian-nils** [comment]
I have v.0.1.8.

I use resize="true", but the issue is that it only works when I resize the browser's window. I was after a method that would update the canvas whenever the parent's size was changed (not necessarily 1:1 with window's resize event).

I solve that using the method "this.$ref.renderer.three.setSize(width, height)".

Thanks for looking into it. We can close the issue if you feel that it should not be modified.

Merci et bonne soirée!

/CN

**Comment by klevron** [comment]
I let this issue open to remind me to improve the doc :)
