### ISSUE TITLE
InstancedMesh material color not working

### ISSUE THREAD

**Issue by SaFrMo** [troisjs/trois#25]
See [here](https://codesandbox.io/s/compassionate-yonath-30sfd?file=/src/App.vue) for example. The weird thing is, if I run this locally, it won't work on the first try, but it will if I change the material:

https://user-images.githubusercontent.com/5344587/111841659-b2d9e200-88d4-11eb-8a88-77b892115f00.mp4

**Comment by SaFrMo** [comment]
I was able to get it to work by changing [this line](https://github.com/troisjs/trois/blob/master/src/materials/Material.js#L23) from

```js
this.mesh.setMaterial(this.material);
```

to

```js
this.$nextTick(() => this.mesh.setMaterial(this.material));
```

I don't think that's a long-term fix, but I wanted to pass it along to play around with later!

**Comment by klevron** [comment]
Nice catch, the problem : material is created before InstancedMesh
With `imesh.material.needsUpdate = true;` it works, but we have to find a better way to handle this

**Comment by SaFrMo** [comment]
See #26 for a possible solution

**Comment by klevron** [comment]
#27
