### ISSUE TITLE
Add option to update pointer every frame

### ISSUE THREAD

**Issue by klevron** [troisjs/trois#35]
Actually it is updated on move.

**Comment by klevron** [comment]
Added `intersectMode` option to be able to intersect objects every frame : 

```html
<Renderer :pointer="{ intersectMode: 'frame' }">
```

Don't know yet if it is a good idea, any thoughts on this @SaFrMo ?

**Comment by klevron** [comment]
Added doc : https://troisjs.github.io/guide/meshes/events.html

**Comment by SaFrMo** [comment]
@klevron Absolutely love the `intersectMode` option and implementation on renderer and raycast, those handle defaults well while still giving control for overrides. Great work on these!
