### ISSUE TITLE
Don't use optional chaining ?

### ISSUE THREAD

**Issue by klevron** [troisjs/trois#42]
To keep using bundlephobia ? https://github.com/pastelsky/bundlephobia/issues/413

**Comment by LXSMNSYC** [comment]
Probable solution is to set the build target into a lower version like es2017

**Comment by klevron** [comment]
This will be fixed soon, I will use rollup-plugin-esbuild (and a lower target) for the next release

**Comment by klevron** [comment]
https://bundlephobia.com/result?p=troisjs@0.3.0-beta.0
