### ISSUE TITLE
Renderer before/after render...

### ISSUE THREAD

**Issue by klevron** [troisjs/trois#43]
I don't know yet if it is a good idea but we could add events to Renderer :
- @before/after render
- @after-resize

This implies we don't need anymore to add a ref to renderer to animate things.
And we could use `renderer.$onBeforeRender`...  to add multiple callbacks.

troisjs is still early stage, I don't think it will be a problem if we change this now.

**Comment by SaFrMo** [comment]
This definitely makes sense - have you looked into whether there's any extra cost for doing this like there was for reactivity in #17 ? I'm happy to do so in the next couple days if not!

**Comment by klevron** [comment]
Well, with the typescript refactoring I was thinking may be it's better to add :
- `addEventListener(type: 'init' | 'mounted' | 'beforerender' | 'afterrender' | 'resize', callback)`
- `removeEventListener(type: 'init' | 'mounted' | 'beforerender' | 'afterrender' | 'resize', callback)`

https://github.com/troisjs/trois/blob/d10c7d6a0242111537b249ad6bb921c9dcd64583/src/core/Renderer.ts

**Comment by klevron** [comment]
Renderer event api with 0.3.0-beta.0 :

-  onInit(cb: InitCallbackType): void
-  onMounted(cb: MountedCallbackType): void

-  onBeforeRender(cb: RenderCallbackType): void
-  offBeforeRender(cb: RenderCallbackType): void
-  onAfterRender(cb: RenderCallbackType): void
-  offAfterRender(cb: RenderCallbackType): void

-  onResize(cb: ResizeCallbackType): void
-  offResize(cb: ResizeCallbackType): void

- addListener<T extends keyof EventCallbackMap>(t: T, cb: EventCallbackMap[T]): void
- removeListener<T extends keyof EventCallbackMap>(t: T, cb: EventCallbackMap[T]): void

Example : 
```js
this.$refs.renderer.onBeforeRender(() => {})
```

Not consistent with renderer props :
- onReady: Function as PropType<(r: RendererInterface) => void>
- onClick: Function as PropType<(this: HTMLCanvasElement, ev: MouseEvent) => any>

But I don't know if we need more events props.
@SaFrMo feel free to comment if you have time
