### ISSUE TITLE
Existing VueJS 3 project

### ISSUE THREAD

**Issue by Tronological** [troisjs/trois#50]
Looks like there is some issue with using Trois in projects that already exist. I tried both the import and declare in main process as well as the direct import in the component and I get the same error both ways. I did download the starter app and that worked but I'm more interested in including Trois in my own bundle. I looked up the error in the source and it apparently has something to do with the intersect function. I did try adding Vite and ViteJS plugin-vue to no effect. The error says something about not having a proper loader but I'm not sure that is what the issue is since I tried Vite and it seems the start app is a pretty barebones implementation.

```
error  in ./node_modules/troisjs/build/trois.module.js

Module parse failed: Unexpected token (128:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|           onIntersectOver(overEvent);
|           onIntersectEnter(enterEvent);
>           component.onPointerOver?.(overEvent);
|           component.onPointerEnter?.(enterEvent);
|         }

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/router/views/Home.vue?vue&type=script&lang=js 3:0-84 9:9-12 10:12-18 11:21-36 12:16-26 13:14-22 14:11-16
 @ ./src/router/views/Home.vue?vue&type=script&lang=js
 @ ./src/router/views/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.113:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by klevron** [comment]
Thanks for reporting this, your bundler don't handle optional chaining (es2020), I think I will have to rewrite some part of the code to avoid this kind of side effect. Related to #42

**Comment by Tronological** [comment]
Appreciate the fast response. I'll look into changing the build chain version. Looks like I might have to go to an older version of webpacks. Here is my package list just in case you notice something similar with other post versions in post #42 

```
{
  "name": "atenreign",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "three": "^0.127.0",
    "troisjs": "^0.2.3",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-e2e-cypress": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/test-utils": "^2.0.0-0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "prettier": "^2.2.1",
    "typescript": "~3.9.3",
    "vue-jest": "^5.0.0-0"
  }
}
```

**Comment by klevron** [comment]
This will be fixed soon, I will use rollup-plugin-esbuild (and a lower target) for the next release

**Comment by rhughes42** [comment]
Great to hear that this is going to get fixed, I'm having the same issue.

**Comment by klevron** [comment]
Can you try with 0.3.0-beta.0 ?
It should be ok now : https://bundlephobia.com/result?p=troisjs@0.3.0-beta.0

**Comment by Tronological** [comment]
Confirmed. I tested both methods of importing the module and they both worked just fine in my custom build. Appreciate your speedy response and effort to fix this.
