### ISSUE TITLE
Materials refactoring

### ISSUE THREAD

**Issue by klevron** [troisjs/trois#54]
Instead duplicating properties from three materials, it should be easier to use a generic `props` prop, e.g. :

```html
<BasicMaterial color="#ffffff" :props="{ transparent: true, opacity: 0.2 }">
```

But keeping a `color` prop is useful.

I think this design pattern will be used for other components.
I will keep some props (geometries is a good example) to have a good ts/ide support.

**Comment by SaFrMo** [comment]
Absolutely love this idea, seems very flexible this way!

**Comment by klevron** [comment]
Nearly done for materials, but I should try to add interfaces for `props` (like the `uniforms` interface in https://github.com/troisjs/trois/blob/master/src/materials/SubSurfaceMaterial.ts), it is really handy for code completion
