### ISSUE TITLE
Raycaster not working on sphere

### ISSUE THREAD

**Issue by c-is** [troisjs/trois#55]
First of all, thank you for an amazing library. It feels so easy to use yet pretty much customisable!
I'm still new to three.js so I'm not sure if my issue is related to this library. Appoligies if it's not the case.

I'm trying to raycasting sphere to add some click points on it, but if I place a 2d object with particular position set, the raycaster doesn't recoginise the object. I had some research and I found some hints on the web and wanted to add `recursive` parameter `true` to `intersectObjects` of the raycaster instance. However, looking into your code, there is no way to add this option using your library (correct me if I'm wrong). I wonder if that's unnecessary or it's simply not added at this moment or I'm doing something completely wrong.

The code bellow is the minimum part of what I'm trying to add. If I remove this position prop and render it in a default position, this onclick event works

```
const position = {
 x: radius * Math.sin(phi) * Math.cos(theta),
 y: 1,
 z: radius * Math.cos(phi),
};

<box :position="position" :scale="scale" @click="onClick">
 <basicMaterial color="#fff" />
</box>
```

Thank you in advance.

**Comment by klevron** [comment]
Hi, Thanks for using troisjs and reporting this 👍 
I will try this soon, what version do you use ?

**Comment by klevron** [comment]
Added an option to handle recursive intersect.

But I can't reproduce your problem, can you show me more code ? what about the sphere ?

**Comment by c-is** [comment]
Thanks for a quick response! I have to tell you that it was due to my stupid mistake. I set the scale something like `{ x: 1, y: 1, z: 0}` for some reason at some point and it wasn't recognised, well, because z was 0.
Sorry for the mess and thank you for adding the option.
