### ISSUE TITLE
shaderMaterial uniforms prop not work

### ISSUE THREAD

**Issue by elineeen** [troisjs/trois#61]
in version 0.2.3 the material props work well like the code below
`            <ShaderMaterial
                        :vertexShader="curlNoiseVertexShader"
                        :uniforms="curNoiseUniforms"
                        :fragmentShader="curlNoiseFragmentShader"
                         />`
but after updated to 0.3 the uniforms cannot be passed to the instance with the same code. I checked the ref instance to find out the vertexShader & fragmentShader work well, but uniforms appers to be the inital empty object. i also get a vue warning like this:
[Vue warn]: Extraneous non-props attributes (vertexShader, uniforms, fragmentShader) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

so is there anything should be changed in this usage?

**Comment by klevron** [comment]
Thanks for using troisjs and reporting this.
I made a few BC in 0.3, you should use `props` :

```html
<ShaderMaterial :props="{ vertexShader: curlNoiseVertexShader, uniforms: curNoiseUniforms, fragmentShader: curlNoiseFragmentShader }" />
```

**Comment by AlbanCrepel** [comment]
I had the same problem, I tried to migrate to v0.3 but had tons of errors (not just the one with `ShaderMaterial` but others as well, like `Missing parent Mesh` or ` Cannot set property '...' of undefined`). I don't mind breaking changes between versions but the doc should be updated. A migration guide in a changelog or something would be nice.

BTW, I LOVE the lib, congrats for the awesome work ! ✨

**Comment by klevron** [comment]
@AlbanCrepel : Does your code work now ? Feel free to create another issue, I will take a look.

Sorry didn't have time to update the docs yet, and troisjs is still early stage so it was time for these BC.
Thanks for using troisjs by the way :)
