### ISSUE TITLE
Some chunks are larger than 500kb after minification.

### ISSUE THREAD

**Issue by Savitar1926** [troisjs/trois#68]
Awesome Library!

I tried to build the app, but I somehow get this error:
Some chunks are larger than 500kb after modification.

Got any ways to fix it? Thanks!

**Comment by klevron** [comment]
Hi, thanks, not really an error, just a rollup warning
I didnt have time to dig into this for the moment :

    Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
