### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by SaFrMo** [troisjs/trois#7]
I use [groups](https://threejs.org/docs/index.html#api/en/objects/Group) a lot when organizing my Three.js scenes and would love to use them here as well with a `<Group>` component:

```
<!-- A road with a car -->
<Scene>
  <Plane ref="road">...</Plane>
  
  <Group id="car-1>
    <Box ref="car1_body">...</Box>
    <Torus ref="car1_wheel_front_l>...</Torus>
    <Torus ref="car1_wheel_front_r>...</Torus>
    <Torus ref="car1_wheel_back_l>...</Torus>
    <Torus ref="car1_wheel_back_r>...</Torus>
  </Group>
</Scene>
```

(Eventually I'd love to be able to place a group into a self-contained component - so for example:

```
[app.vue]
<Scene>
  <Plane ref="road">...</Plane>
  
  <Car id="car-1"/>
  <Car id="car-2"/>
</Scene

[car.vue]
<Group>
  <Box ref="car_body">...</Box>
  <Torus ref="car_wheel_front_l>...</Torus>
  [...]
</Group>
```

but that can be a later goal!)

Happy to take this on if you'd like, I just wanted to make sure this wasn't already in the works or anything. Thanks so much!

**Comment by klevron** [comment]
Thanks for the idea and the PR 👍
