### ISSUE TITLE
The requested module '/node_modules/.vite/troisjs.497662d1.js' does not provide an export named 'VRButton'

### ISSUE THREAD

**Issue by Slyvan25** [troisjs/trois#75]
![image](https://user-images.githubusercontent.com/12664592/122910117-2406b680-d356-11eb-8265-bdb1ee982c2d.png)

Maybe this is something I did wrong but the VRButton doesn't get imported.
do I have to import the button or is it imported in the package?

**Comment by klevron** [comment]
You should import it like this :  `import VRButton from 'troisjs/src/components/misc/VRButton.vue'`
And set xr attribute on renderer.

Sorry, I didn't had time to add example (#16 )

**Comment by Slyvan25** [comment]
> 
> 
> You should import it like this : `import VRButton from 'troisjs/src/components/misc/VRButton.vue'`
> And set xr attribute on renderer.
> 
> Sorry, I didn't had time to add example (#16 )

Will the VRButton be a part of the default components any time soon? (vite doesn't like deep imports)
