### ISSUE TITLE
Unable to pause/resume animation (cancelAnimationFrame)

### ISSUE THREAD

**Issue by vesamet** [troisjs/trois#79]
### Problem
Can't seem to find a way to simply pause/resume the request animation frame.

Looking at the code of  `trois/src/core/Renderer.ts` : , the requestAnimationFrame() function isn't bound/exposed to any variable and therefore i can't pass the raf id the cancelAnimationFrame() function.

Is there a way to do so that i'm not aware of,?

### Possible solution
Exposing the local variable `raf` of `Renderer.ts` as a synced props?

### Use case:
I'm rendering an instanciatedMesh of 200k+ cubes, but the scene is static (except when moving the camera)
[Here is an image of my stress test scene](https://i.ibb.co/gWccjs8/Screen-2021-07-13-13-25-35.png)

**Comment by oneWaveAdrian** [comment]
Can you access https://threejs.org/docs/#api/en/renderers/WebGLRenderer.setAnimationLoop via the https://troisjs.github.io/guide/core/renderer.html#access-threejs-renderer?

If so you could set it to `0` as per THREE documentation to pause your animations?

**Comment by vesamet** [comment]
Thanks. Passing `null` to `.renderer.setAnimationLoop()` did the job. Now I just need to find how to turn the animation back on :)

**Comment by oneWaveAdrian** [comment]
@vesamet Just pass your animation function into the parameter or toggle a variable between `null` to stop and the callback function to start (https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#notes)

**Comment by oneWaveAdrian** [comment]
@vesamet did it work?

**Comment by vesamet** [comment]
@oneWaveAdrian 
Sorry was in the woods. 
Yes, thank you for your help! 💯

**Comment by oneWaveAdrian** [comment]
@vesamet great! Wanna close the issue then? :)
