### ISSUE TITLE
Raycaster question

### ISSUE THREAD

**Issue by subbe98** [troisjs/trois#87]
Is there a way to only trigger an event on the closest object(in terms of distance) when the raycaster intersects multiple objects? I have a problem where it triggers events on boxes behind the intended object even after removing the prop intersect-recursive on the raycaster component.

**Comment by SaFrMo** [comment]
Thanks for your question! There's no built-in way to do this, but I believe the raycaster keeps its array of collisions sorted from closest to farthest - would it be possible in your use case to use just the first element in that array? Or to check in the event if the target is the first in that array?

**Comment by subbe98** [comment]
I think that is the best solution as well, and I did learn about the intersectObjects array in the threejs docs. But I am having trouble finding this array and viewing its elements in troisjs. The raycaster component is made with <Raycaster/>, but do I put a ref="" on the component to access the array in the script tags, or how do I find it?

**Comment by OleksiiBrylin** [comment]
@subbe98 @SaFrMo Do you have an example how to use the raycaster? 
The raycaster doesn't return an array of intersects.

```
<Renderer
        ref="renderer"
        :pointer="{
          intersectRecursive: true,
        }"
        antialias
        :orbit-ctrl="true"
        resize="window"
      >
        <Camera :aspect="1" :position="{ x: 1.5, y: 3, z: 5 }" :fov="75" :near="0.1" :far="1000" />
        <Scene>
          <AmbientLight :intensity="0.5" />
          <SpotLight :position="{ x: 10, y: 15, z: 10 }" :angle="0.3" />
          <Raycaster
            intersect-mode="move"
            :intersect-objects="iObjects"
            :pointer="{
              intersectRecursive: true,
            }"
            @pointerOver="onPointerEvent"
          />

          <Box :position="{ x: 0, y: -1.4, z: 0 }">
            <LambertMaterial :props="{ transparent: true, opacity: 0.1 }" :color="'red'" />
          </Box>

          <Box :position="{ x: 0, y: 0, z: 0 }">
            <LambertMaterial :props="{ transparent: true, opacity: 0.1 }" :color="'green'" />
          </Box>

        </Scene>
      </Renderer>
```
