### ISSUE TITLE
Retina / HDPI screens

### ISSUE THREAD

**Issue by okydk** [troisjs/trois#88]
Currently scenes looks pixelated on iPhones and Retina macs.
It would be great if the renderer took the `window.devicePixelRatio` into account when resizing the canvas. 😀

**Comment by klevron** [comment]
We should may be use this by default : `renderer.setPixelRatio( window.devicePixelRatio );`

**Comment by SaFrMo** [comment]
Adding a dpr option, with a fallback to detecting and using the window's dpr, makes sense to me!

**Comment by klevron** [comment]
Sorry I am really late of this one.
Added a `pixelRatio` prop : https://github.com/troisjs/trois/commit/60eee1a544c92c20301c9a3ffaebea0498bdf75a
I will release asap 0.3.4
