### ISSUE TITLE
Triosjs to Nuxt 3

### ISSUE THREAD

**Issue by differentMonster** [troisjs/trois#95]
do anyone tried to pass in Triosjs package to Nuxt 3, i cant get it work, here is the testing github. Before i tried to pass into nuxt 2 but triosjs only support Vue 3, now nuxt 3 support Vue 3, it should be working right ?

https://github.com/differentMonster/nuxt3-troisjs.git

the error i have is : Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/troisjs.js?v=2804f0f5' does not provide an export named 'default'

thanks will be greatful :D let me know, what i miss out ya.

**Comment by klevron** [comment]
You should use `import { TroisJSVuePlugin } from "troisjs"`

**Comment by differentMonster** [comment]
@klevron i tried before but somehow noting show as well, could you help me look at it ? Will be greatful.

**Comment by klevron** [comment]
https://github.com/troisjs/nuxt3-test

**Comment by differentMonster** [comment]
@klevron thanks Klevron, i tried again with you advice now it work, but the folder was the same as before not sure what i missing out last time. but greatful for you github klevron, it helps alot, please stay healthy and weathly k.
