### ISSUE TITLE
ThreeJS  Dependency Errors when Building Application

### ISSUE THREAD

**Issue by MikeyGInTheMorning** [troisjs/trois#99]
Using both starter project zips from the installation page and using Troisjs as a component create this error when building the application. Was able to reproduce error on another machine by using a starter project.

![image](https://user-images.githubusercontent.com/14945840/141610013-99277548-c477-4166-9dc6-c2cc74919706.png)

Error Text:
`
    Pre-bundling dependencies:
  vue
  troisjs
(this will be run only when your dependencies or config have changed)
 > node_modules/troisjs/build/trois.module.js:6:29: error: Could not resolve "three/examples/jsm/geometries/TextGeometry.js" (mark it as external to exclude it from the 
bundle)
    6 │ import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry.js';
      ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > node_modules/troisjs/build/trois.module.js:7:27: error: Could not resolve "three/examples/jsm/loaders/FontLoader.js" (mark it as external to exclude it from the bundle)
    7 │ import { FontLoader } from 'three/examples/jsm/loaders/FontLoader.js';
      ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 2 errors:
node_modules/troisjs/build/trois.module.js:6:29: error: Could not resolve "three/examples/jsm/geometries/TextGeometry.js" (mark it as external to exclude it from the bundle)
node_modules/troisjs/build/trois.module.js:7:27: error: Could not resolve "three/examples/jsm/loaders/FontLoader.js" (mark it as external to exclude it from the bundle) 
    at failureErrorWithLog (C:\Source\mg-vue-bucket\mg-vue-bucket\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Source\mg-vue-bucket\mg-vue-bucket\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (C:\Source\mg-vue-bucket\mg-vue-bucket\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (C:\Source\mg-vue-bucket\mg-vue-bucket\node_modules\esbuild\lib\main.js:1149:7)
    at C:\Source\mg-vue-bucket\mg-vue-bucket\node_modules\esbuild\lib\main.js:1258:14
    at C:\Source\mg-vue-bucket\mg-vue-bucket\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\Source\mg-vue-bucket\mg-vue-bucket\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\Source\mg-vue-bucket\mg-vue-bucket\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mg-vue-bucket@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!`

**Comment by MikeyGInTheMorning** [comment]
Further reviewing the issue, in trois.module.js, the imports  on  lines are:
```
import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry.js';
import { FontLoader } from 'three/examples/jsm/loaders/FontLoader.js';
```

and should be:
```
import { TextGeometry } from 'three/src/geometries/TextGeometry.js';
import { FontLoader } from 'three/src/loaders/FontLoader.js';
```

**Comment by MikeyGInTheMorning** [comment]
One quick additional note to mention is that in troisjs repo, three is referenced as "three": "^0.134.0", while the other packages have  "three": "0.127.0",

**Comment by oneWaveAdrian** [comment]
@klevron issue persists, manual change as suggested by @MikeyGInTheMorning is still necessary using TroisJS `V0.3.4`

> ```
> import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry.js';
> import { FontLoader } from 'three/examples/jsm/loaders/FontLoader.js';
> ```
> **=>**
> ```
> import { TextGeometry } from 'three/src/geometries/TextGeometry.js';
> import { FontLoader } from 'three/src/loaders/FontLoader.js';
> ```
